create database `INDIANELECTION`;
-- Entity tables

-- create table party

CREATE TABLE PARTY(
    PARTY_ID INT NOT NULL,
    PARTY_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY(PARTY_ID)
);


-- create table candidate

CREATE TABLE CANDIDATE(
    CANDIDATE_ID INT NOT NULL,
    CANDIDATE_NAME VARCHAR(255) NOT NULL,
    CANDIDATE_STATUS VARCHAR(15) NOT NULL,
    PRIMARY KEY(CANDIDATE_ID)
);

-- create table election

CREATE TABLE ELECTION(
    ELECTION_ID INT NOT NULL,
    ELECTION_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY(ELECTION_ID)
);
-- create table consituency

CREATE TABLE CONSTITUENCY(
    CONSTITUENCY_ID INT NOT NULL,
    CONSTITUENCY_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY(CONSTITUENCY_ID)
);
-- create table state

CREATE TABLE STATES(
 STATE_ID INT NOT NULL,
 STATE_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (STATE_ID)
);
-- create table electionType

CREATE TABLE ELECTIONTYPE(
 ELECTIONTYPE_ID INT NOT NULL,
 ELECTIONTYPE_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ELECTIONTYPE_ID)
);

-- relationship table

-- create table party_candidate

CREATE TABLE PARTY_CANDIDATE(
 PARTY_ID INT NOT NULL REFERENCES PARTY(PARTY_ID),
 CANDIDATE_ID INT NOT NULL REFERENCES CANDIDATE(CANDIDATE_ID),
 CONSTRAINT PARTY_CANDIDATE_ID PRIMARY KEY (PARTY_ID, CANDIDATE_ID)   
);

-- create table contituency_candidate
CREATE TABLE CONSTITUENCY_CANDIDATE(
 CONSTITUENCY_ID INT NOT NULL REFERENCES CONSTITUENCY(CONSTITUENCY_ID),
 CANDIDATE_ID INT NOT NULL REFERENCES CANDIDATE(CANDIDATE_ID),
 CONSTRAINT CONSTITUENCY_CANDIDATE_ID PRIMARY KEY (CONSTITUENCY_ID, CANDIDATE_ID)   
);

-- create table state_constituency
CREATE TABLE STATES_CONSTITUENCY(
 STATE_ID INT NOT NULL REFERENCES STATES(STATE_ID),
 CONSTITUENCY_ID INT NOT NULL REFERENCES CONSTITUENCY(CONSTITUENCY_ID),
 CONSTRAINT STATES_CONSTITUENCY_ID PRIMARY KEY (STATE_ID, CONSTITUENCY_ID)   
);

-- create table electionType_constituency
CREATE TABLE ELECTIONTYPE_CONSTITUENCY(
 ELECTIONTYPE_ID INT NOT NULL REFERENCES ELECTIONTYPE(ELECTIONTYPE_ID),
 CONSTITUENCY_ID INT NOT NULL REFERENCES CONSTITUENCY(CONSTITUENCY_ID),
 CONSTRAINT ELECTIONTYPE_CONSTITUENCY_ID PRIMARY KEY (ELECTIONTYPE_ID, CONSTITUENCY_ID)   
);

-- create table electionType_state
CREATE TABLE ELECTIONTYPE_STATES(
 ELECTIONTYPE_ID INT NOT NULL REFERENCES ELECTIONTYPE(ELECTIONTYPE_ID),
 STATE_ID INT NOT NULL REFERENCES STATES(STATE_ID),
 CONSTRAINT ELECTIONTYPE_STATES_ID PRIMARY KEY (STATE_ID, ELECTIONTYPE_ID)   
);

-- create table election_electionType
CREATE TABLE ELECTION_ELECTIONTYPE(
 ELECTION_ID INT NOT NULL REFERENCES ELECITON(ELECTION_ID),
 ELECTIONTYPE_ID INT NOT NULL REFERENCES ELECTIONTYPE(ELECTIONTYPE_ID),
 CONSTRAINT ELECTION_ELECTIONTYPE_ID PRIMARY KEY (ELECTION_ID, ELECTIONTYPE_ID)   
);

-- create table election_state
CREATE TABLE ELECTION_STATES(
 ELECTION_ID INT NOT NULL REFERENCES ELECITON(ELECTION_ID),
 STATE_ID INT NOT NULL REFERENCES STATES(STATE_ID),
 CONSTRAINT ELECTION_STATES_ID PRIMARY KEY (ELECTION_ID, STATE_ID)   
);


-- Insert Query -- 

INSERT INTO `states` (`state_id`, `state_name`) VALUES
(1, 'ANDHRA PRADESH'),
(2, 'ASSAM'),
(3, 'ARUNACHAL PRADESH'),
(4, 'BIHAR'),
(5, 'GUJRAT'),
(6, 'HARYANA'),
(7, 'HIMACHAL PRADESH'),
(8, 'JAMMU & KASHMIR'),
(9, 'KARNATAKA'),
(10, 'KERALA'),
(11, 'MADHYA PRADESH'),
(12, 'MAHARASHTRA'),
(13, 'MANIPUR'),
(14, 'MEGHALAYA'),
(15, 'MIZORAM'),
(16, 'NAGALAND'),
(17, 'ORISSA'),
(18, 'PUNJAB'),
(19, 'RAJASTHAN'),
(20, 'SIKKIM'),
(21, 'TAMIL NADU'),
(22, 'TRIPURA'),
(23, 'UTTAR PRADESH'),
(24, 'WEST BENGAL'),
(25, 'DELHI'),
(26, 'GOA'),
(27, 'PONDICHERY'),
(28, 'LAKSHDWEEP'),
(29, 'DAMAN & DIU'),
(30, 'DADRA & NAGAR'),
(31, 'CHANDIGARH'),
(32, 'ANDAMAN & NICOBAR'),
(33, 'UTTARANCHAL'),
(34, 'JHARKHAND'),
(35, 'CHATTISGARH');